(()=>{'use strict';
const WORKER='https://projectv-storage.hrhw55tdmw.workers.dev';
const CHUNK_SIZE=32*1024*1024,CONCURRENCY=2,MAX_RETRIES=12,VERSION=3;
const $=id=>document.getElementById(id);
const ui={picker:$('picker'),fileBox:$('fileBox'),fileName:$('fileName'),fileMeta:$('fileMeta'),start:$('start'),test:$('test'),connection:$('connection'),topStatus:$('topStatus'),progressCard:$('progressCard'),resumeBanner:$('resumeBanner'),percent:$('percent'),fill:$('fill'),state:$('state'),substate:$('substate'),checkpoint:$('checkpoint'),uploaded:$('uploaded'),speed:$('speed'),part:$('part'),eta:$('eta'),pause:$('pause'),resume:$('resume'),abort:$('abort'),log:$('log')};
let file=null,session=null,paused=false,abortRequested=false,running=false,autoPaused=false;
let activeXHRs=new Map(),inflightBytes=new Map(),speedSamples=[],lastAggregateTime=performance.now(),lastAggregateBytes=0;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const fmtBytes=n=>{if(!Number.isFinite(n)||n<=0)return'0 B';const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i>=3?2:i===2?1:0)} ${u[i]}`};
const fmtTime=s=>{if(!Number.isFinite(s)||s<0)return'—';s=Math.round(s);const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;if(h)return`${h}h ${m}m`;if(m)return`${m}m ${sec}s`;return`${sec}s`};
const safeName=name=>name.replace(/[\\/]+/g,'_').replace(/[^a-zA-Z0-9._()\- ]/g,'_').slice(0,180)||'archive.7z';
const sessionKey=f=>`projectv:r2:v${VERSION}:${f.name}:${f.size}:${f.lastModified}`;
const legacyKeys=f=>[`projectv:r2:v2:${f.name}:${f.size}:${f.lastModified}`,`projectv:r2:${f.name}:${f.size}:${f.lastModified}`];
const log=msg=>{const time=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});ui.log.textContent=`${time}  ${msg}\n`+ui.log.textContent.slice(0,7000)};
function save(){if(!file||!session)return;try{session.updatedAt=Date.now();localStorage.setItem(sessionKey(file),JSON.stringify(session));localStorage.setItem('projectv:r2:last',JSON.stringify({name:file.name,size:file.size,lastModified:file.lastModified,parts:Object.keys(session.parts||{}).length,total:Math.ceil(file.size/CHUNK_SIZE),updatedAt:Date.now()}))}catch(e){log(`Warning: resume state could not be saved (${e.message}).`)}}
function clearSaved(){if(!file)return;localStorage.removeItem(sessionKey(file));for(const k of legacyKeys(file))localStorage.removeItem(k);localStorage.removeItem('projectv:r2:last')}
function savedSummary(){try{return JSON.parse(localStorage.getItem('projectv:r2:last')||'null')}catch{return null}}
async function api(path,opts={}){const r=await fetch(WORKER+path,{cache:'no-store',...opts}),text=await r.text();let data;try{data=JSON.parse(text)}catch{data={error:text||`HTTP ${r.status}`}}if(!r.ok){const e=new Error(data.error||`HTTP ${r.status}`);e.status=r.status;throw e}return data}
function setConnection(ok,text){ui.connection.textContent=text;ui.topStatus.textContent=text;ui.connection.className='online '+(ok?'ok':'bad');ui.topStatus.className='status-pill '+(ok?'ok':'bad')}
async function testConnection(){ui.connection.textContent='Checking…';ui.topStatus.textContent='Checking…';ui.connection.className='online';ui.topStatus.className='status-pill';try{const h=await api('/');if(!h.ok||!h.multipart)throw new Error('Multipart API unavailable');await api('/files?prefix=source/');setConnection(true,'R2 online');log('Worker and R2 connection OK.');return true}catch(e){setConnection(false,navigator.onLine?'R2 unavailable':'No network');log(`Connection failed: ${e.message}`);return false}}
function partSize(n){const start=(n-1)*CHUNK_SIZE;return Math.max(0,Math.min(CHUNK_SIZE,file.size-start))}
function committedBytes(){if(!file||!session)return 0;return Object.keys(session.parts||{}).reduce((s,k)=>s+partSize(Number(k)),0)}
function inflightTotal(){let n=0;for(const v of inflightBytes.values())n+=v;return n}
function updateProgress({committedOnly=false}={}){if(!file||!session)return;const committed=committedBytes();const visual=Math.min(file.size,committed+(committedOnly?0:inflightTotal()));const pct=file.size?visual/file.size*100:0;const total=Math.ceil(file.size/CHUNK_SIZE),finished=Object.keys(session.parts||{}).length;
  ui.percent.textContent=`${pct.toFixed(pct>=10?1:2)}%`;ui.fill.style.width=`${pct}%`;ui.uploaded.textContent=`${fmtBytes(visual)} / ${fmtBytes(file.size)}`;ui.checkpoint.textContent=`${fmtBytes(committed)} • ${finished}/${total} parts`;ui.part.textContent=`${finished} / ${total}`;ui.substate.textContent=finished?`Checkpoint saved at part ${finished}`:'No completed part yet';
  const now=performance.now(),dt=(now-lastAggregateTime)/1000;if(dt>=.65){const delta=Math.max(0,visual-lastAggregateBytes),speed=delta/dt;lastAggregateTime=now;lastAggregateBytes=visual;if(speed>0&&!committedOnly){speedSamples.push(speed);if(speedSamples.length>8)speedSamples.shift();const avg=speedSamples.reduce((a,b)=>a+b,0)/speedSamples.length;ui.speed.textContent=`${fmtBytes(avg)}/s`;ui.eta.textContent=fmtTime((file.size-visual)/avg)}}
}
function loadSession(f){let raw=localStorage.getItem(sessionKey(f));if(!raw){for(const k of legacyKeys(f)){raw=localStorage.getItem(k);if(raw)break}}if(!raw)return null;try{const s=JSON.parse(raw);if(s.fileSize===f.size&&s.uploadId&&s.chunkSize===CHUNK_SIZE){s.version=VERSION;s.parts=s.parts||{};log(`Restored ${Object.keys(s.parts).length} completed parts from local checkpoint.`);return s}}catch{}return null}
function showSavedHint(){const s=savedSummary();if(!s)return;const when=s.updatedAt?new Date(s.updatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'earlier';ui.resumeBanner.textContent=`Saved upload found: ${s.name} • ${s.parts||0}/${s.total||'?'} parts • last checkpoint ${when}. Select the same file to restore it.`;ui.resumeBanner.classList.add('show')}
ui.picker.addEventListener('change',()=>{const f=ui.picker.files?.[0];if(!f)return;file=f;session=loadSession(f);paused=false;abortRequested=false;autoPaused=false;running=false;activeXHRs.clear();inflightBytes.clear();speedSamples=[];lastAggregateBytes=session?committedBytes():0;lastAggregateTime=performance.now();ui.fileName.textContent=f.name;ui.fileMeta.textContent=`${fmtBytes(f.size)} • ${Math.ceil(f.size/CHUNK_SIZE)} parts • 32 MiB each • ${CONCURRENCY} parallel streams`;ui.fileBox.classList.add('show');ui.progressCard.classList.add('show');ui.start.disabled=!!session;ui.resume.disabled=!session;ui.pause.disabled=true;ui.abort.disabled=!session;ui.state.textContent=session?'Checkpoint restored':'Ready to upload';ui.resumeBanner.classList.toggle('show',!!session);if(session)ui.resumeBanner.textContent=`Resume ready. ${Object.keys(session.parts).length}/${Math.ceil(f.size/CHUNK_SIZE)} completed parts are already committed in R2.`;updateProgress({committedOnly:true})});
async function createSession(){const key=`source/${safeName(file.name)}`,data=await api(`/multipart/${encodeURIComponent(key)}?action=create`,{method:'POST'});session={version:VERSION,key,uploadId:data.uploadId,fileName:file.name,fileSize:file.size,lastModified:file.lastModified,chunkSize:CHUNK_SIZE,parts:{},createdAt:Date.now(),updatedAt:Date.now()};save();log(`Multipart session created for ${key}.`)}
function abortActiveRequests(){for(const xhr of activeXHRs.values())try{xhr.abort()}catch{}activeXHRs.clear();inflightBytes.clear();updateProgress({committedOnly:true})}
function uploadPartXHR(partNumber,blob){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest;activeXHRs.set(partNumber,xhr);xhr.open('PUT',`${WORKER}/multipart/${encodeURIComponent(session.key)}?action=part&uploadId=${encodeURIComponent(session.uploadId)}&partNumber=${partNumber}`,true);xhr.responseType='text';xhr.timeout=180000;xhr.upload.onprogress=e=>{if(e.lengthComputable){inflightBytes.set(partNumber,e.loaded);updateProgress()}};const cleanup=()=>{activeXHRs.delete(partNumber);inflightBytes.delete(partNumber);updateProgress()};xhr.onload=()=>{let data={};try{data=JSON.parse(xhr.responseText||'{}')}catch{}cleanup();if(xhr.status>=200&&xhr.status<300&&data.etag)resolve(data);else{const e=new Error(data.error||`Part ${partNumber} failed (${xhr.status})`);e.status=xhr.status;reject(e)}};xhr.onerror=()=>{cleanup();reject(new Error(`Network error on part ${partNumber}`))};xhr.ontimeout=()=>{cleanup();reject(new Error(`Part ${partNumber} timed out`))};xhr.onabort=()=>{cleanup();reject(new DOMException('Aborted','AbortError'))};xhr.send(blob)})}
async function waitForNetwork(){while(!navigator.onLine){ui.state.textContent='Waiting for network';setConnection(false,'No network');await new Promise(resolve=>{const h=()=>{window.removeEventListener('online',h);resolve()};window.addEventListener('online',h,{once:true})})}if(autoPaused){ui.state.textContent='Reconnecting…';let ok=false;for(let i=0;i<8&&!ok;i++){ok=await testConnection();if(!ok)await sleep(Math.min(8000,1000*Math.pow(1.5,i)))}if(ok){autoPaused=false;ui.state.textContent='Resuming…';log('Connection restored. Resuming from committed checkpoint.')}}}
async function uploadWithRetry(partNumber,blob){for(let attempt=1;attempt<=MAX_RETRIES;attempt++){if(paused||abortRequested)throw new DOMException('Stopped','AbortError');await waitForNetwork();try{return await uploadPartXHR(partNumber,blob)}catch(e){if(e.name==='AbortError'){if(autoPaused&&!paused&&!abortRequested){log(`Part ${partNumber} paused by network change. Waiting to resume from checkpoint.`);await waitForNetwork();attempt--;continue}throw e}if(e.status===404&&/upload|multipart|not found/i.test(e.message||'')){const stale=new Error('Saved multipart session no longer exists in R2. Abort locally and start a new upload.');stale.code='STALE_SESSION';throw stale}if(attempt===MAX_RETRIES)throw e;autoPaused=true;ui.state.textContent='Reconnecting…';updateProgress({committedOnly:true});const wait=Math.min(15000,850*Math.pow(1.7,attempt-1));log(`Part ${partNumber} interrupted. Retry ${attempt}/${MAX_RETRIES} in ${(wait/1000).toFixed(1)}s.`);await sleep(wait)}}}
async function uploadOnePart(partNumber,total){if(session.parts[partNumber])return;const start=(partNumber-1)*CHUNK_SIZE,end=Math.min(file.size,start+CHUNK_SIZE),blob=file.slice(start,end);log(`Uploading part ${partNumber}/${total} (${fmtBytes(blob.size)}).`);const result=await uploadWithRetry(partNumber,blob);session.parts[partNumber]={partNumber:result.partNumber,etag:result.etag,size:blob.size,completedAt:Date.now()};save();updateProgress({committedOnly:true});log(`Part ${partNumber} committed. Checkpoint saved.`)}
async function parallelUpload(total){const queue=[];for(let n=1;n<=total;n++)if(!session.parts[n])queue.push(n);let cursor=0,fatal=null;async function workerLoop(){while(true){if(fatal||paused||abortRequested)return;const i=cursor++;if(i>=queue.length)return;try{await uploadOnePart(queue[i],total)}catch(e){if(e.name==='AbortError'&&(paused||abortRequested))return;fatal=e;abortActiveRequests();return}}}const workers=[];for(let i=0;i<Math.min(CONCURRENCY,queue.length);i++)workers.push(workerLoop());await Promise.all(workers);if(fatal)throw fatal}
async function verifyFinalObject(){const listing=await api('/files?prefix=source/'),obj=(listing.objects||[]).find(o=>o.key===session.key);if(!obj)throw new Error('Final R2 object was not found during verification.');if(Number(obj.size)!==Number(file.size))throw new Error(`Final size mismatch: R2 has ${fmtBytes(obj.size)}, expected ${fmtBytes(file.size)}.`);log(`Verified final R2 object size: ${fmtBytes(obj.size)}.`)}
async function runUpload({newSession=false}={}){if(!file||running)return;running=true;try{if(newSession||!session)await createSession();paused=false;abortRequested=false;autoPaused=false;speedSamples=[];lastAggregateBytes=committedBytes();lastAggregateTime=performance.now();ui.start.disabled=true;ui.pause.disabled=false;ui.resume.disabled=true;ui.abort.disabled=false;ui.state.textContent='Uploading';const total=Math.ceil(file.size/CHUNK_SIZE);await parallelUpload(total);if(abortRequested){ui.state.textContent='Aborting…';return}if(paused){ui.state.textContent='Paused safely';ui.pause.disabled=true;ui.resume.disabled=false;ui.abort.disabled=false;updateProgress({committedOnly:true});log(`Paused at checkpoint ${Object.keys(session.parts).length}/${total}. Interrupted partial parts will restart on Resume.`);return}const parts=Object.values(session.parts).map(p=>({partNumber:p.partNumber,etag:p.etag})).sort((a,b)=>a.partNumber-b.partNumber);if(parts.length!==total)throw new Error(`Only ${parts.length}/${total} parts are complete.`);ui.state.textContent='Finalizing';ui.pause.disabled=true;log('All parts committed. Asking R2 to assemble the object…');const result=await api(`/multipart/${encodeURIComponent(session.key)}?action=complete&uploadId=${encodeURIComponent(session.uploadId)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({parts})});inflightBytes.clear();updateProgress({committedOnly:true});await verifyFinalObject();ui.percent.textContent='100%';ui.fill.style.width='100%';ui.uploaded.textContent=`${fmtBytes(file.size)} / ${fmtBytes(file.size)}`;ui.state.textContent='Upload complete';ui.substate.textContent='Verified in R2';ui.speed.textContent='Done';ui.eta.textContent='0s';ui.pause.disabled=true;ui.resume.disabled=true;ui.abort.disabled=true;clearSaved();log(`Complete: ${result.key} (${fmtBytes(result.size||file.size)}).`);session=null}catch(e){if(e.name==='AbortError'&&(paused||abortRequested)){if(paused){ui.state.textContent='Paused safely';ui.pause.disabled=true;ui.resume.disabled=false;ui.abort.disabled=false;updateProgress({committedOnly:true})}return}ui.state.textContent=e.code==='STALE_SESSION'?'Session expired':'Error';ui.start.disabled=false;ui.pause.disabled=true;ui.resume.disabled=!session;ui.abort.disabled=!session;log(`ERROR: ${e.message}`)}finally{running=false}}
ui.start.addEventListener('click',()=>runUpload({newSession:true}));
ui.pause.addEventListener('click',()=>{if(!session||!running)return;paused=true;ui.state.textContent='Saving checkpoint…';ui.pause.disabled=true;abortActiveRequests();save()});
ui.resume.addEventListener('click',async()=>{if(!file||!session||running)return;paused=false;abortRequested=false;autoPaused=false;ui.state.textContent='Checking connection…';updateProgress({committedOnly:true});const ok=await testConnection();if(!ok&&!navigator.onLine){autoPaused=true;ui.state.textContent='Waiting for network'}runUpload()});
ui.abort.addEventListener('click',async()=>{if(!session||!confirm('Abort this multipart upload? Completed parts for this session will be discarded.'))return;abortRequested=true;paused=false;abortActiveRequests();ui.state.textContent='Aborting';try{await api(`/multipart/${encodeURIComponent(session.key)}?action=abort&uploadId=${encodeURIComponent(session.uploadId)}`,{method:'DELETE'})}catch(e){log(`R2 abort request: ${e.message}`)}clearSaved();session=null;inflightBytes.clear();ui.percent.textContent='0%';ui.fill.style.width='0';ui.checkpoint.textContent='0 B';ui.uploaded.textContent='0 B';ui.part.textContent='0 / 0';ui.speed.textContent='—';ui.eta.textContent='—';ui.state.textContent='Aborted';ui.substate.textContent='No checkpoint';ui.start.disabled=false;ui.pause.disabled=true;ui.resume.disabled=true;ui.abort.disabled=true;ui.resumeBanner.classList.remove('show');log('Multipart session cleared.')});
ui.test.addEventListener('click',testConnection);
window.addEventListener('offline',()=>{setConnection(false,'No network');if(running&&!paused){autoPaused=true;ui.state.textContent='Waiting for network';abortActiveRequests();log('Network dropped. Upload paused at the latest committed checkpoint.')}});
window.addEventListener('online',async()=>{ui.state.textContent=running?'Reconnecting…':ui.state.textContent;const ok=await testConnection();if(ok&&running&&autoPaused&&!paused){autoPaused=false;log('Network returned. Active workers will resume from checkpoint.')}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&running)log('Uploader moved to background. iOS may throttle network activity; return to the uploader for maximum reliability.')});
let audioCtx=null,lastTone=-1;
const soundBanks={
  move:[[390,.017,.028,'sine'],[445,.015,.026,'triangle'],[505,.014,.025,'sine'],[560,.013,.024,'triangle'],[620,.012,.022,'sine'],[350,.018,.030,'triangle']],
  accept:[[650,.022,.042,'sine'],[720,.021,.038,'triangle'],[800,.019,.040,'sine'],[880,.018,.043,'triangle'],[600,.023,.036,'sine'],[760,.020,.046,'sine']],
  back:[[220,.020,.044,'sine'],[255,.019,.042,'triangle'],[290,.018,.040,'sine'],[325,.017,.038,'triangle'],[205,.021,.046,'sine'],[345,.016,.036,'sine']]
};
function tone(kind='move'){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const bank=soundBanks[kind]||soundBanks.move;let i=Math.floor(Math.random()*bank.length);if(bank.length>1&&i===lastTone)i=(i+1)%bank.length;lastTone=i;const [hz,vol,len,type]=bank[i],t=audioCtx.currentTime,osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type=type;osc.frequency.setValueAtTime(hz*(.985+Math.random()*.03),t);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(vol,t+.004);gain.gain.exponentialRampToValueAtTime(.0001,t+len);osc.connect(gain);gain.connect(audioCtx.destination);osc.start(t);osc.stop(t+len+.008)}catch{}}
document.querySelectorAll('.tap-control').forEach(el=>el.addEventListener('pointerdown',()=>{if(!el.disabled)tone(el.dataset.sound||'move')},{passive:true}));
document.querySelectorAll('.nav-item').forEach(row=>{const select=()=>{document.querySelectorAll('.nav-item').forEach(r=>r.classList.remove('active'));row.classList.add('active');tone('move');const target=document.getElementById(row.dataset.target);if(target&&target.id!=='connection')target.scrollIntoView({behavior:'smooth',block:'start'})};row.addEventListener('click',select);row.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select()}})});
document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});document.addEventListener('dblclick',e=>e.preventDefault(),{passive:false});document.addEventListener('touchmove',e=>{if(e.touches&&e.touches.length>1)e.preventDefault()},{passive:false});
showSavedHint();
if('serviceWorker'in navigator){navigator.serviceWorker.register('./service-worker.js?v=7').then(reg=>reg.update()).catch(()=>{})}
testConnection();
})();
